fixing shit

diff --git a/tools/opticharger b/tools/opticharger
--- a/tools/opticharger
+++ b/tools/opticharger
@@ -9,22 +9,11 @@
 # cyanogen - shade@chemlab.org
 # ChrisSoyars - me@ctso.me
 
-. $ANDROID_BUILD_TOP/vendor/broken/tools/colors
-
-OUT_TARGET_HOST=$(uname -a | grep Darwin)
-if [ -z "$OUT_TARGET_HOST" ]
-then
-    OUT_TARGET_HOST=linux-x86
-else
-    OUT_TARGET_HOST=darwin-x86
-fi
-
 set -e
 QUIET=1
 BASE=`pwd`
 BRUTECRUSH="-brute"
 TMPDIR=/tmp/opticharge-$$
-NINEPATCH=0
 
 if [ -z "$BRUTE_PNGCRUSH" ]
 then
@@ -42,14 +31,14 @@ then
     APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
     if [ ! -f "$APKCERTS" ];
     then
-        echo -e ${red}"Set APKCERTS to the path to your apkcerts.txt file"${txtrst}
+        echo "Set APKCERTS to the path to your apkcerts.txt file"
         exit 1;
     fi
 fi
 
 if [ ! -f "$APKCERTS" ];
 then
-    echo -e ${red}"Invalid path to apkcerts.txt, set APKCERTS to the correct path."${txtrst}
+    echo "Invalid path to apkcerts.txt, set APKCERTS to the correct path."
 fi
 
 if [ "$(which pngcrush)" != "" ];
@@ -74,26 +63,26 @@ then
         pngout $1
     }
 else
-    echo -e ${red}"Please install pngquant, pngcrush, optipng, or pngout"${txtrst}
+    echo "Please install pngcrush, optipng, or pngout"
     exit 1;
 fi
 
 if [ "`which aapt`" = "" ];
 then
-    echo -e ${red}"Please ensure aapt is in your \$PATH"${txtrst}
+    echo "Please ensure aapt is in your \$PATH"
     exit 1;
 fi
 
 if [ "`which zipalign`" = "" ];
 then
-    echo -e ${red}"Please ensure zipalign is in your \$PATH"${txtrst}
+    echo "Please ensure zipalign is in your \$PATH"
     exit 1;
 fi
 
 if [ -e "$1" ];
 then
     NAME=`basename $1`;
-    echo -e ${bldgrn}"Optimizing:${txtrst} $NAME...";
+    echo "Optimizing $NAME...";
 
     if [ "$2" != "" ];
     then
@@ -101,32 +90,32 @@ then
         KEY=build/target/product/security/$2.pk8
         if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
         then
-            echo -e ${red}"$CERT does not exist!"${txtrst};
+            echo "$CERT does not exist!";
             exit 1;
         fi
     else
         APKINFO=`grep "name=\"$NAME\"" $APKCERTS`;
-        [ $QUIET ] || echo -e "APKINFO: $APKINFO";
+        [ $QUIET ] || echo "APKINFO: $APKINFO";
         if [ "$APKINFO" = "" ];
         then
-            echo -e ${red}"No apk info for $NAME"${txtrst};
+            echo "No apk info for $NAME";
             exit 1;
         fi
-        CERT=`echo -e $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
-        KEY=`echo -e $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
+        CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
+        KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
         if [ "$CERT" = "" ];
         then
-            echo -e ${red}"Unable to find certificate for $NAME"${txtrst}
+            echo "Unable to find certificate for $NAME"
             exit 1;
         fi
         if [ "$CERT" = "PRESIGNED" ];
         then
-            echo -e ${cya}"$NAME is presigned, skipping"${txtrst}
+            echo "$NAME is presigned, skipping"
             exit 1;
         fi
     fi
 
-    [ $QUIET ] || echo -e ${bldylw}"Certificate:${txtrst} $CERT";
+    [ $QUIET ] || echo "Certificate: $CERT";
 
     [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
     mkdir -p $TMPDIR/$NAME
@@ -135,19 +124,19 @@ then
     unzip -q $BASE/$1
     for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
     do
-        [ $QUIET ] || echo -e ${bldgrn}"Crushing${txtrst} $x"
+        [ $QUIET ] || echo "Crushing $x"
         optimize_png $x
     done
     cp $BASE/$1 $BASE/$1.old
 
-    [ $QUIET ] || echo -e ${bldgrn}"Repacking apk.."${txtrst}
-    aapt p -0 .dat -0 .dict -F $NAME .
+    [ $QUIET ] || echo "Repacking apk.."
+    aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .
+    
+    [ $QUIET ] || echo "Resigning with cert: `echo $CERT`"
 
-    [ $QUIET ] || echo -e ${bldgrn}"Resigning with cert:${txtrst} `echo -e $CERT`"
-
-    [ $QUIET ] || echo -e java -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    java -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    [ $QUIET ] || echo -e ${bldgrn}"Zipalign.."${txtrst}
+    [ $QUIET ] || echo java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
+    java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
+    [ $QUIET ] || echo "Zipalign.."
     zipalign -f 4 signed_$NAME $BASE/$1
     if [ ! $QUIET ]; then
         ls -l $BASE/$1.old
@@ -155,6 +144,5 @@ then
     fi
     rm $BASE/$1.old
 else
-    echo -e "Usage: $0 [apk file]"
+    echo "Usage: $0 [apk file]"
 fi
-
